/* ============================================================
   FISIO EXPERT - Libreria esercizi
   ------------------------------------------------------------
   Generato da gestione-esercizi.html il 27/08/2026.
   Meglio modificarlo da quella pagina che a mano.
   ============================================================ */

const AREE = ["Ginocchio", "Anca/Glutei", "Caviglia/Piede", "Ischiocrurali", "Lombare/Core", "Spalla", "Gomito/Polso", "Cervicale"];

const LIBRERIA_ESERCIZI = [
  { nome: "Affondi (lunges)", area: "Ginocchio", serie: "3", rip: "10/lato", riposo: "60s", rpe: "", note: "", desc: "In piedi, fai un passo avanti e piega entrambe le ginocchia fino a circa 90°, mantenendo il busto eretto. Il ginocchio anteriore resta sopra la caviglia. Spingi col tallone anteriore per tornare in piedi." },
  { nome: "Isometrica quadricipite", area: "Ginocchio", serie: "3", rip: "30s", riposo: "60s", rpe: "", note: "", desc: "Da seduto o supino con la gamba distesa, contrai il quadricipite spingendo il cavo del ginocchio verso il basso, come per raddrizzare al massimo la gamba. Mantieni la contrazione senza muovere l'articolazione, poi rilascia." },
  { nome: "Leg extension", area: "Ginocchio", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "", desc: "Da seduto alla macchina o con cavigliera, estendi il ginocchio sollevando la gamba fino a distenderla, poi abbassa controllando il movimento. Concentra lo sforzo sul quadricipite." },
  { nome: "Squat a corpo libero", area: "Ginocchio", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "", desc: "In piedi, piedi alla larghezza delle spalle. Scendi piegando anche e ginocchia come per sederti, mantenendo la schiena dritta e le ginocchia in linea con i piedi. Scendi fino a dove il controllo lo permette, poi risali spingendo coi talloni." },
  { nome: "Squat spagnolo (Spanish squat)", area: "Ginocchio", serie: "3", rip: "30s", riposo: "60s", rpe: "", note: "elastico dietro le ginocchia", desc: "Posiziona una banda elastica resistente dietro le ginocchia, ancorata a un punto fisso davanti a te. Lascia che l'elastico tiri indietro le ginocchia mentre scendi in squat con busto verticale. Mantieni la posizione bassa o esegui ripetizioni lente." },
  { nome: "Step-down controllato", area: "Ginocchio", serie: "3", rip: "10/lato", riposo: "60s", rpe: "", note: "", desc: "In piedi su un gradino, scendi lentamente con una gamba sfiorando il pavimento col tallone senza appoggiare il peso, poi risali controllando il movimento. Mantieni il ginocchio allineato, evita che cada verso l'interno." },
  { nome: "Terminal knee extension (TKE)", area: "Ginocchio", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "elastico", desc: "In piedi con un elastico dietro al ginocchio leggermente piegato, ancorato davanti. Estendi completamente il ginocchio vincendo la resistenza dell'elastico, poi torna lentamente." },
  { nome: "Wall sit (sedia al muro)", area: "Ginocchio", serie: "3", rip: "30-45s", riposo: "60s", rpe: "", note: "", desc: "Schiena appoggiata al muro, scivola verso il basso fino ad avere ginocchia e anche a 90°, come seduto su una sedia invisibile. Mantieni la posizione respirando normalmente." },
  { nome: "Abduzione anca in piedi", area: "Anca/Glutei", serie: "3", rip: "15/lato", riposo: "60s", rpe: "", note: "elastico opzionale", desc: "In piedi, appoggiandoti se serve. Solleva lateralmente una gamba distesa mantenendo il busto fermo e la punta in avanti, poi abbassa controllando. Evita di inclinare il tronco." },
  { nome: "Clamshell (conchiglia)", area: "Anca/Glutei", serie: "3", rip: "15/lato", riposo: "60s", rpe: "", note: "elastico opzionale", desc: "Sul fianco, ginocchia piegate e piedi uniti. Tenendo i piedi a contatto, apri il ginocchio superiore ruotando l'anca, senza far ruotare il bacino all'indietro. Chiudi lentamente." },
  { nome: "Fire hydrant", area: "Anca/Glutei", serie: "3", rip: "12/lato", riposo: "60s", rpe: "", note: "", desc: "In quadrupedia, mantieni il ginocchio piegato e sollevalo lateralmente come un cane all'idrante, senza ruotare la schiena. Abbassa controllando." },
  { nome: "Hip thrust", area: "Anca/Glutei", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "con/senza carico", desc: "Spalle appoggiate a una panca, piedi a terra. Spingi il bacino verso l'alto contraendo i glutei fino a portare il tronco orizzontale, poi abbassa lentamente. Puoi aggiungere un peso sul bacino." },
  { nome: "Monster walk (camminata con elastico)", area: "Anca/Glutei", serie: "3", rip: "10 passi", riposo: "60s", rpe: "", note: "elastico", desc: "Elastico attorno alle caviglie o sopra le ginocchia, leggero squat. Cammina lateralmente o in avanti mantenendo tensione costante sull'elastico e le ginocchia allineate." },
  { nome: "Ponte glutei (glute bridge)", area: "Anca/Glutei", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "", desc: "Supino, ginocchia piegate e piedi a terra. Solleva il bacino contraendo i glutei fino ad allineare spalle-anche-ginocchia, poi abbassa lentamente senza appoggiare completamente." },
  { nome: "Ponte glutei monopodalico", area: "Anca/Glutei", serie: "3", rip: "10/lato", riposo: "60s", rpe: "", note: "", desc: "Come il ponte glutei, ma con una gamba sollevata e distesa. Spingi col tallone a terra per sollevare il bacino mantenendolo orizzontale, senza farlo ruotare." },
  { nome: "Calf raise (rialzi sul polpaccio)", area: "Caviglia/Piede", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "", desc: "In piedi, sollevati sulle punte dei piedi il più in alto possibile contraendo i polpacci, poi abbassa lentamente i talloni. Per progredire, esegui su una sola gamba o su un gradino." },
  { nome: "Calf raise monopodalico", area: "Caviglia/Piede", serie: "3", rip: "12/lato", riposo: "60s", rpe: "", note: "", desc: "Su una gamba sola, sollevati sulla punta del piede controllando l'equilibrio, poi abbassa lentamente. Appoggia un dito a una parete se serve stabilità." },
  { nome: "Dorsiflessione con elastico", area: "Caviglia/Piede", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "elastico", desc: "Seduto con gamba distesa, elastico attorno all'avampiede ancorato davanti. Tira la punta del piede verso di te vincendo la resistenza, poi rilascia lentamente." },
  { nome: "Equilibrio monopodalico", area: "Caviglia/Piede", serie: "3", rip: "30s/lato", riposo: "60s", rpe: "", note: "", desc: "In piedi su una gamba sola, mantieni l'equilibrio il più a lungo possibile. Per progredire chiudi gli occhi o appoggiati su una superficie morbida." },
  { nome: "Eversione/inversione con elastico", area: "Caviglia/Piede", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "elastico", desc: "Con elastico attorno all'avampiede, ruota il piede verso l'esterno (eversione) o verso l'interno (inversione) contro resistenza, mantenendo la gamba ferma." },
  { nome: "Heel-to-toe walk (tandem)", area: "Caviglia/Piede", serie: "3", rip: "10 passi", riposo: "60s", rpe: "", note: "", desc: "Cammina in linea retta appoggiando il tallone di un piede subito davanti alla punta dell'altro, come su una fune, mantenendo l'equilibrio." },
  { nome: "Stretch del polpaccio al muro", area: "Caviglia/Piede", serie: "3", rip: "30s/lato", riposo: "60s", rpe: "", note: "", desc: "Mani al muro, una gamba indietro tesa col tallone a terra e l'altra piegata avanti. Spingi il bacino verso il muro fino a sentire allungamento nel polpaccio posteriore." },
  { nome: "Hamstring bridge (ponte ischiocrurali)", area: "Ischiocrurali", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "talloni su rialzo", desc: "Supino con i talloni su una panca o step, gambe semitese. Solleva il bacino spingendo coi talloni, sentendo lavorare la parte posteriore della coscia, poi abbassa lentamente." },
  { nome: "Nordic hamstring", area: "Ischiocrurali", serie: "3", rip: "6", riposo: "60s", rpe: "", note: "caviglie bloccate", desc: "In ginocchio con le caviglie tenute ferme da un partner o un fermo. Scendi lentamente in avanti resistendo con gli ischiocrurali il più possibile, poi spingiti su con le mani." },
  { nome: "Romanian deadlift (stacco rumeno)", area: "Ischiocrurali", serie: "3", rip: "10", riposo: "60s", rpe: "", note: "manubri/bilanciere", desc: "In piedi con peso davanti alle cosce. Spingi il bacino indietro abbassando il peso lungo le gambe con la schiena dritta e ginocchia poco piegate, fino a sentire tensione dietro le cosce, poi risali." },
  { nome: "Stretching ischiocrurali supino", area: "Ischiocrurali", serie: "3", rip: "30s/lato", riposo: "60s", rpe: "", note: "", desc: "Supino, solleva una gamba tesa aiutandoti con le mani o un asciugamano dietro la coscia, fino a sentire allungamento dietro la coscia. Mantieni senza rimbalzi." },
  { nome: "Bird dog", area: "Lombare/Core", serie: "3", rip: "10/lato", riposo: "60s", rpe: "", note: "", desc: "In quadrupedia, estendi contemporaneamente braccio destro e gamba sinistra fino all'orizzontale mantenendo il bacino stabile, poi cambia lato. Evita di ruotare il tronco." },
  { nome: "Cat-camel (gatto-cammello)", area: "Lombare/Core", serie: "3", rip: "10", riposo: "60s", rpe: "", note: "", desc: "In quadrupedia, alterna inarcamento della schiena verso l'alto (gatto) e inarcamento verso il basso (cammello) in modo lento e fluido, accompagnando col respiro." },
  { nome: "Curl-up addominale", area: "Lombare/Core", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "", desc: "Supino, una gamba piegata e una distesa, mani sotto la zona lombare. Solleva leggermente testa e spalle contraendo gli addominali senza flettere il collo, poi abbassa lentamente." },
  { nome: "Dead bug", area: "Lombare/Core", serie: "3", rip: "10/lato", riposo: "60s", rpe: "", note: "", desc: "Supino, braccia verso il soffitto e ginocchia a 90°. Abbassa lentamente braccio e gamba opposti mantenendo la zona lombare aderente al pavimento, poi torna e cambia." },
  { nome: "Esercizio di McKenzie (estensione prona)", area: "Lombare/Core", serie: "3", rip: "10", riposo: "60s", rpe: "", note: "", desc: "Prono, mani all'altezza delle spalle. Spingi sulle braccia estendendo la schiena e sollevando il busto mentre il bacino resta a terra, poi torna giù lentamente. Fermati se i sintomi si irradiano di più." },
  { nome: "Pelvic tilt (basculamento bacino)", area: "Lombare/Core", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "", desc: "Supino, ginocchia piegate. Appiattisci la zona lombare contro il pavimento contraendo gli addominali e ruotando leggermente il bacino, poi rilascia." },
  { nome: "Plank (frontale)", area: "Lombare/Core", serie: "3", rip: "30s", riposo: "60s", rpe: "", note: "", desc: "Appoggiato su avambracci e punte dei piedi, corpo in linea retta dalle spalle ai talloni. Contrai addome e glutei evitando di inarcare o far cadere il bacino. Respira normalmente." },
  { nome: "Respirazione Diaframmatica", area: "Lombare/Core", serie: "5-7", rip: "1'", riposo: "30\"", rpe: "7", note: "Respirazione: 3\" inspirazione, 3\" pausa, 4\" espiro, 4\" pausa", desc: "In posizione supina con le gambe flesse cominciare a respirare normalmente. Metti le dita poco sotto l'ombelico e applica una leggera pressione per stimolare l'addome a contrarsi. Comincia a respirare cercando di mantenere dolcemente attivo l'addome durante tutta la durata dell'esercizio." },
  { nome: "Side plank (laterale)", area: "Lombare/Core", serie: "3", rip: "30s/lato", riposo: "60s", rpe: "", note: "", desc: "Sul fianco, appoggiato su un avambraccio. Solleva il bacino formando una linea retta dalla testa ai piedi, mantenendo la posizione senza ruotare il tronco." },
  { nome: "Full can", area: "Spalla", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "manubri leggeri", desc: "Braccia tese sul piano scapolare con pollici verso l'alto, solleva fino all'altezza delle spalle mantenendo il controllo e le scapole basse, poi abbassa." },
  { nome: "Pendolo di Codman", area: "Spalla", serie: "3", rip: "30s", riposo: "60s", rpe: "", note: "", desc: "Busto flesso in avanti appoggiando una mano a un tavolo, lascia pendere il braccio dolente rilassato. Disegna piccoli cerchi e oscillazioni sfruttando lo slancio del corpo, non i muscoli della spalla." },
  { nome: "Retrazione scapolare (rowing elastico)", area: "Spalla", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "elastico", desc: "Elastico ancorato davanti a te all'altezza del petto. Tira i gomiti indietro avvicinando le scapole, mantenendo le spalle basse, poi rilascia lentamente." },
  { nome: "Rotazione esterna con elastico", area: "Spalla", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "gomito al fianco", desc: "In piedi, gomito piegato a 90° aderente al fianco, elastico ancorato lateralmente. Ruota l'avambraccio verso l'esterno mantenendo il gomito fermo al corpo, poi torna lentamente." },
  { nome: "Rotazione interna con elastico", area: "Spalla", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "gomito al fianco", desc: "Gomito al fianco a 90°, elastico ancorato dal lato opposto. Ruota l'avambraccio verso l'addome contro resistenza, mantenendo il gomito aderente al corpo." },
  { nome: "Scaption (elevazione sul piano scapolare)", area: "Spalla", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "manubri leggeri", desc: "In piedi, solleva le braccia tese a circa 30° avanti rispetto ai fianchi (a 'V'), pollici in alto, fino all'altezza delle spalle, poi abbassa controllando." },
  { nome: "Sleeper stretch", area: "Spalla", serie: "3", rip: "30s", riposo: "60s", rpe: "", note: "", desc: "Sul fianco del lato dolente, spalla e gomito a 90°. Con l'altra mano spingi delicatamente l'avambraccio verso il basso per allungare la capsula posteriore, senza forzare il dolore." },
  { nome: "Wall slide (scivolamento al muro)", area: "Spalla", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "", desc: "Avambracci appoggiati al muro a 'W'. Fai scivolare le braccia verso l'alto fino a una 'Y' mantenendo il contatto e abbassando le scapole, poi torna giù." },
  { nome: "Estensione polso eccentrica (epicondilite)", area: "Gomito/Polso", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "manubrio leggero", desc: "Avambraccio appoggiato, palmo verso il basso, manubrio in mano. Alza il polso, poi abbassalo molto lentamente (fase eccentrica) controllando il peso. Aiutati con l'altra mano a risalire." },
  { nome: "Flessione polso eccentrica (epitrocleite)", area: "Gomito/Polso", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "manubrio leggero", desc: "Avambraccio appoggiato, palmo verso l'alto. Solleva il polso, poi abbassalo lentamente controllando il peso nella fase di discesa." },
  { nome: "Presa (squeeze) con pallina", area: "Gomito/Polso", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "pallina/gripper", desc: "Stringi una pallina morbida o un gripper con la mano, mantieni la contrazione un paio di secondi e rilascia. Utile per forza di presa e tendinopatie del gomito." },
  { nome: "Stretching estensori del polso", area: "Gomito/Polso", serie: "3", rip: "30s", riposo: "60s", rpe: "", note: "", desc: "Braccio teso davanti, palmo verso il basso. Con l'altra mano piega il polso verso il basso fino a sentire allungamento sul dorso dell'avambraccio. Mantieni senza dolore acuto." },
  { nome: "Supinazione/pronazione con peso", area: "Gomito/Polso", serie: "3", rip: "15", riposo: "60s", rpe: "", note: "martello/manubrio", desc: "Gomito al fianco a 90°, impugna un manubrio asimmetrico o un martello. Ruota lentamente l'avambraccio palmo su e palmo giù, controllando in entrambe le direzioni." },
  { nome: "Chin tuck (retrazione cervicale)", area: "Cervicale", serie: "3", rip: "10", riposo: "60s", rpe: "", note: "", desc: "Seduto o in piedi, sguardo all'orizzonte. Porta il mento indietro creando un 'doppio mento' senza inclinare la testa, come per allungare la nuca. Mantieni qualche secondo e rilascia." },
  { nome: "Isometrica cervicale multidirezionale", area: "Cervicale", serie: "3", rip: "5s x dir.", riposo: "60s", rpe: "", note: "", desc: "Appoggia la mano sulla fronte, sulla nuca e sui lati della testa a turno. Spingi la testa contro la mano senza muoverla (contrazione isometrica), mantenendo qualche secondo per ogni direzione." },
  { nome: "Retrazione scapole seduto", area: "Cervicale", serie: "3", rip: "12", riposo: "60s", rpe: "", note: "", desc: "Seduto con schiena dritta, avvicina le scapole tra loro abbassandole, come per stringere una matita tra le scapole. Mantieni qualche secondo e rilascia, senza alzare le spalle." },
  { nome: "Stretching trapezio superiore", area: "Cervicale", serie: "3", rip: "30s/lato", riposo: "60s", rpe: "", note: "", desc: "Seduto, inclina la testa di lato avvicinando l'orecchio alla spalla, aiutandoti delicatamente con la mano. Mantieni la spalla opposta bassa fino a sentire allungamento sul collo." }
];
